-- Pagina publică „Prestatori": ce se arată despre fiecare firmă.
--
-- Lista a pornit dintr-o căutare făcută pe 30 septembrie 2026: site-urile
-- firmelor, lista de distribuitori Egger (egger.com/ro/distribuitori) și
-- registrul comerțului. „recomandat" = debitare și cant cu dovezi, de obicei
-- și CNC, firmă activă de cel puțin 5 ani; „verificat" = de verificat: pare
-- bună, dar dovezile sunt puține. Administratorul le schimbă din
-- Administrare → Prestatori.

ALTER TABLE prestatori ADD COLUMN orase       TEXT;            -- toate orașele, pentru pagina publică
ALTER TABLE prestatori ADD COLUMN regiune     TEXT;            -- moldova | transilvania | banat | sud | dobrogea | nationale
ALTER TABLE prestatori ADD COLUMN verdict     TEXT NOT NULL DEFAULT 'verificat';  -- recomandat | verificat
ALTER TABLE prestatori ADD COLUMN din_an      INTEGER;
ALTER TABLE prestatori ADD COLUMN marime      TEXT;            -- „46 de angajați"
ALTER TABLE prestatori ADD COLUMN cnc         INTEGER NOT NULL DEFAULT 0;
ALTER TABLE prestatori ADD COLUMN excel       INTEGER NOT NULL DEFAULT 0;  -- primește listă Excel
ALTER TABLE prestatori ADD COLUMN egger       INTEGER NOT NULL DEFAULT 0;  -- pe lista de distribuitori Egger
ALTER TABLE prestatori ADD COLUMN cum_comanda TEXT;
ALTER TABLE prestatori ADD COLUMN descriere   TEXT;
ALTER TABLE prestatori ADD COLUMN site        TEXT;
ALTER TABLE prestatori ADD COLUMN public      INTEGER NOT NULL DEFAULT 1;  -- apare pe pagina „Prestatori"
ALTER TABLE prestatori ADD COLUMN verificat_la TEXT;

INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'HTC Cubbis', 'Iași', 'Iași', 'moldova', 'recomandat', 2014, '46 de angajați', 1, 0, 0, 'debitare, cant ABS 0,4–2 mm, CNC', 'Comandă pe email, cu schițe cotate — le trimite aplicația.', 'Debitare PAL, MDF, HDF, HPL. Cant și pe curbe. Livrare cu șoferi proprii.', 'office@cubbis.ro', '0745 073 618', 'https://cubbis.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'HTC Cubbis');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Global Design · FrontMDF', 'Suceava', 'Suceava', 'moldova', 'recomandat', 2001, '83 de angajați', 1, 0, 1, 'debitare, cant zero-joint, CNC nesting', 'Formular de comandă trimis pe email.', 'Utilaje Homag cu AirTec. Lucrează doar în județul Suceava.', 'servicii.debitare@frontmdf.ro', '0374 476 000', 'https://www.frontmdf.ro/servicii/', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Global Design · FrontMDF');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Fabrikart', 'Constanța', 'Constanța', 'dobrogea', 'recomandat', 2000, '43 de angajați', 1, 0, 0, 'debitare, cant ABS, 2 CNC', 'Email sau cerere de ofertă pe site.', 'Homag cu încărcare automată, cantuitoare Brandt.', 'office@fabrikart.ro', '0756 086 393', 'https://fabrikart.ro/servicii-prelucrare.html', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Fabrikart');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Johanes Qualitat', 'Cluj-Napoca', 'Cluj-Napoca', 'transilvania', 'recomandat', 2006, '36 de angajați', 1, 1, 0, 'debitare, cant ABS 0,8–2 mm, CNC', 'Listă de croire pe email.', 'Homag Sawteq și Edgeteq, cu prefrezare. Nu aplică cant de 0,4 mm.', 'debitare@johanesqualitat.ro', '0725 954 073', 'https://johanesqualitat.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Johanes Qualitat');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Woodexpert', 'Cluj-Napoca', 'Cluj-Napoca', 'transilvania', 'recomandat', 2008, '21 de angajați', 1, 1, 0, 'debitare, cant ABS 0,4–2 mm, CNC', 'Formular Excel pe email.', 'Cant Egger.', 'office@woodexpertcluj.ro', '0725 520 552', 'https://woodexpertcluj.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Woodexpert');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'ProfiCut', 'Timișoara', 'Timișoara', 'banat', 'recomandat', 2007, '14 angajați', 1, 0, 0, 'debitare, cant ABS drept și curb, CNC', 'Email sau formular pe site.', 'Egger, Kronospan, Kastamonu.', 'office@proficut.ro', '0740 015 691', 'https://www.proficut.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'ProfiCut');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'PalHause', 'Timișoara', 'Timișoara · Nădlac', 'banat', 'recomandat', 2004, '9 angajați', 1, 0, 0, 'debitare, cant ABS, CNC', 'Email sau cont de client pe site.', 'Două ferăstraie Biesse Selco.', 'office@palhause.ro', '0722 526 768', 'https://palhause.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'PalHause');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'C3 Concept Cut', 'Arad', 'Arad', 'banat', 'recomandat', 2017, 'firmă în creștere', 1, 0, 0, 'debitare, cant ABS, CNC', 'Email, formular sau telefon.', 'Homag, imos și CutRite.', 'office@conceptcut.ro', '0748 557 596', 'https://conceptcut.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'C3 Concept Cut');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Holver', 'Chiajna', 'Chiajna · Cluj · Iași · Brașov · Timișoara', 'nationale', 'recomandat', 2000, '313 angajați', 1, 1, 1, 'debitare, cant PUR 0,4–2 mm, frezare, găurire', 'Configurator online WebCut sau formular Excel.', 'Cant doar cu adeziv PUR.', 'holver@holver.ro', '021 407 94 00', 'https://www.holver.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Holver');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Woody.ro', 'Pantelimon', 'Pantelimon · Cernica', 'sud', 'recomandat', 2017, '34 de angajați', 1, 0, 0, 'debitare, cant ABS 0,4–2 mm, CNC', 'Email sau formular de contact.', 'Linie completă Homag, cant Egger cu prefrezare.', 'contact@woody.ro', '0373 013 222', 'https://woody.ro/servicii-debitare-cantuire-cnc/', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Woody.ro');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Brico Wood Trade', 'Pitești', 'Pitești · Craiova', 'sud', 'recomandat', 2014, '57 de angajați', 1, 0, 0, 'debitare, cant, găurire, frezare', 'Email sau magazin online.', 'Livrare cu mașini proprii în sud și sud-vest.', 'office@bricowoodtrade.ro', '0348 800 131', 'https://bricowoodtrade.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Brico Wood Trade');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Regency Company', 'București', 'București · Ploiești · Brașov · Cluj · Sibiu · Bacău · Craiova', 'nationale', 'recomandat', 1999, '317 angajați', 0, 1, 1, 'debitare, cant ABS 0,4–2 mm, fără CNC', 'Șablon Excel propriu, pe email sau încărcat pe site.', 'Piese între 20×20 și 2770×2040 mm.', 'office@regencycompany.ro', '021 9779', 'https://regencycompany.ro/informatii-debitare', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Regency Company');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Darel', 'București', 'București · Brașov · Sibiu', 'nationale', 'recomandat', 1992, '68 de angajați', 0, 0, 1, 'debitare, cant ABS 0,4–2 mm, găurire', 'Lista de debitare pe emailul fiecărui punct.', 'Prețuri publicate. CNC doar pentru îmbinarea blaturilor.', 'debitare.darel@gmail.com', '0736 107 063', 'https://www.darel.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Darel');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Ecopal', 'Pitești', 'Pitești · București · Brașov · Timișoara', 'nationale', 'recomandat', 2003, '61 de angajați', 1, 0, 1, 'debitare, cant, găurire CNC', 'Pe emailul fiecărei sucursale.', 'Linii Homag, blaturi HPL. Adresa de aici e a sucursalei București.', 'ecopal_b@ecopal.ro', '0747 030 707', 'https://www.ecopal.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Ecopal');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Tectona', 'Târgu Mureș', 'Târgu Mureș · Cluj-Napoca · Satu Mare', 'transilvania', 'recomandat', 1993, '34 de angajați', 1, 0, 1, 'debitare, cant ABS, frezare CNC', 'Email sau telefon.', 'Nu publică un format de comandă.', 'comercial@tectona.ro', '0721 458 847', 'https://www.tectona.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Tectona');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Arabesque Wood', 'București', 'București · Iași · Cluj · Brașov · Craiova · Timișoara și alte orașe', 'nationale', 'verificat', 1994, 'rețea națională', 0, 0, 1, 'debitare, cant ABS/PVC, proiectare AMOB', 'La depozit sau pe emailul fiecărui centru.', 'Livrare în 12–24 h. CNC neconfirmat.', '', '0374 012 345', 'https://arabesque.ro/public/servicii/debitare-si-cantuire-placi', 0, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Arabesque Wood');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Trady 2000', 'București', 'Iași · Cluj · Timișoara · Brașov · București · Constanța · Craiova', 'nationale', 'verificat', 1999, '241 de angajați', 0, 0, 0, 'debitare, cant', 'Email sau telefon la depozitul local.', 'Nu publică grosimi de cant sau CNC.', 'office@trady.ro', '', 'https://trady.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Trady 2000');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Dancomp', 'Buzău', 'Buzău', 'sud', 'verificat', 1994, 'firmă mică', 1, 1, 0, 'debitare, cant ABS 0,4–2 mm, găurire, frezare', 'Formular Excel pe email.', 'Cifră de afaceri mică în 2024.', 'contact@dancomp.ro', '0723 894 107', 'https://www.dancomp.ro/debitare-si-cantuire-pal-mdf', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Dancomp');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Nouă Tei', 'Râmnicu Sărat', 'Râmnicu Sărat', 'sud', 'verificat', 1994, '117 angajați', 0, 0, 0, 'debitare, cant ABS', 'Telefon sau formular pe site.', 'Livrează în Vrancea, Brăila, Galați.', 'contact@nouatei.ro', '0751 220 020', 'https://nouatei.ro/servicii/debitare-pal-si-aplicare-cant-abs/', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Nouă Tei');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Decopal Exim', 'București', 'București', 'sud', 'verificat', 2016, '13 angajați', 0, 0, 0, 'debitare, cant ABS/PVC 0,4–2 mm', 'Email sau telefon.', 'Egger, Kronospan, Kastamonu.', 'office@decopal.ro', '0755 140 470', 'https://www.decopal.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Decopal Exim');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Depozitul de accesorii', 'București', 'București', 'sud', 'verificat', 2005, 'date neclare', 1, 0, 0, 'debitare, cant ABS, CNC', 'Magazin online sau email.', 'Proiectare în IMOS.', 'vanzari@depozitul-de-accesorii.ro', '0754 229 775', 'https://depozitul-de-accesorii.ro/6-servicii', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Depozitul de accesorii');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'debitare-pal.ro', 'Miercurea Ciuc', 'Miercurea Ciuc · livrare în toată țara', 'transilvania', 'verificat', 2011, '14 angajați', 1, 0, 0, 'debitare, cant ABS 0,4–2 mm, găurire CNC', 'Doar prin configuratorul lor online.', 'Livrare națională în 48–72 h.', '', '0731 035 689', 'https://debitare-pal.ro', 0, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'debitare-pal.ro');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'KT Mobilier', 'Brașov', 'Brașov', 'transilvania', 'verificat', 2013, 'firmă mică', 0, 0, 0, 'debitare, cant ABS 0,4–2 mm', 'Email sau telefon, cel mult 5 zile.', '', 'office@ktmobilier.ro', '0723 844 069', 'https://ktmobilier.ro/servicii/debitare-si-cantuire/', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'KT Mobilier');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Holzcut Joshua', 'Târgu Mureș', 'Târgu Mureș', 'transilvania', 'verificat', NULL, 'date lipsă', 1, 0, 0, 'debitare, cant PUR, CNC', 'Email sau telefon.', 'Etichetează piesele.', 'holzcutjoshua@gmail.com', '0747 872 563', 'https://www.debitarepal-mures.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Holzcut Joshua');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Artepal EGM', 'Galați', 'Galați', 'moldova', 'verificat', 2019, '10 angajați', 0, 0, 0, 'debitare, cant laser', 'Doar Facebook și telefon.', '', '', '', 'https://www.facebook.com/artepal.egm/', 0, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Artepal EGM');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Mobilier Tudora', 'Ploiești', 'Ploiești', 'sud', 'verificat', 2018, 'firmă mică', 1, 0, 0, 'debitare, cant, găurire, frezare', 'Email pentru ofertă.', '', 'comenzi@mobiliertudora.ro', '0729 489 271', 'https://mobiliertudora.ro/shop/debitare-cantuire-mdf-pal/', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Mobilier Tudora');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Proterm-Line', 'Bistrița', 'Bistrița · Sântion (Bihor)', 'transilvania', 'verificat', 2000, '32 de angajați', 1, 0, 1, 'debitare, cant Airtec, CNC', 'Comandă online și fișier de debitare, cu cont.', 'De confirmat cantul ABS pe PAL.', 'office@protermline.ro', '0751 166 811', 'http://www.protermline.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Proterm-Line');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Euro Est Decorative', 'Suceava', 'Suceava · Constanța', 'moldova', 'verificat', 2019, '38 de angajați', 1, 0, 1, 'debitare, cant laser 0,4–2 mm, CNC nesting', 'Email, telefon sau showroom.', 'Serviciile apar doar pe site-ul vechi.', 'office@euroestdecorative.ro', '0755 904 746', 'https://palsiaccesorii.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Euro Est Decorative');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Florencio', 'Oradea', 'Oradea', 'banat', 'verificat', 2003, '7 angajați', 0, 0, 1, 'debitare, cant', 'Email sau telefon.', 'Tipul de cant nu e publicat.', 'florencio.oradea@yahoo.com', '0359 177 569', 'https://florencio.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Florencio');
INSERT INTO prestatori (nume, oras, orase, regiune, verdict, din_an, marime, cnc, excel, egger, servicii, cum_comanda, descriere, email, telefon, site, activ, public, verificat_la)
  SELECT 'Metalcom', 'Craiova', 'Craiova', 'sud', 'verificat', 1994, '76 de angajați', 0, 0, 1, 'debitare, cant', 'Schiță de debitare pe email.', '', 'office@metalcom.ro', '0753 073 314', 'https://www.metalcom.ro', 1, 1, '2026-09-30' WHERE NOT EXISTS (SELECT 1 FROM prestatori WHERE nume = 'Metalcom');
